<?php
/**
 * Field definitions: LocalBusiness (Schema.org LocalBusiness).
 *
 * @package Nexter_Extension
 * @subpackage Content_SEO
 */

defined( 'ABSPATH' ) || exit;

require_once __DIR__ . '/local-business-subtypes.php';
require_once __DIR__ . '/local-business-selects.php';

return array(
	array(
		'key'     => '@id',
		'label'   => __( 'ID', 'nexter-extension' ),
		'input'   => 'text',
		'tooltip' => __( 'A unique ID for this schema. You can use the page URL or leave the default value as it is.', 'nexter-extension' ),
		'default' => '%site.url%#localbusiness-%schema.item.id%',
	),
	array(
		'key'     => '@type',
		'label'   => __( 'Business Type', 'nexter-extension' ),
		'input'   => 'select_group',

		'default' => 'LocalBusiness',
		'options' => nexter_content_seo_schema_local_business_subtype_groups(),
	),
	array(
		'key'     => 'additionalType',
		'label'   => __( 'Additional Type', 'nexter-extension' ),
		'input'   => 'string_list',
		'tooltip' => __( 'Add any extra types for the business (one per row).', 'nexter-extension' ),
		'default' => array(),
	),
	array(
		'key'     => 'name',
		'label'   => __( 'Business Name', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Enter the full name of the local business.', 'nexter-extension' ),
		'default' => '%site.title%',
	),
	array(
		'key'     => 'description',
		'label'   => __( 'Description', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Write a short summary about the business and its services.', 'nexter-extension' ),
		'default' => '%site.description%',
	),
	array(
		'key'     => 'url',
		'label'   => __( 'Business URL', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Add the link to the main business website.', 'nexter-extension' ),
		'default' => '%site.url%',
	),
	array(
		'key'     => 'image',
		'label'   => __( 'Images', 'nexter-extension' ),
		'input'   => 'string_list',
		'tooltip' => __( 'Add image URLs related to the business (one per row).', 'nexter-extension' ),
		'default' => array(),
	),
	array(
		'key'     => 'logo',
		'label'   => __( 'Logo', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Add the URL of the business logo image.', 'nexter-extension' ),
		'default' => '%website_details.website_logo%',
	),
	array(
		'key'     => 'servesCuisine',
		'label'   => __( 'Serves Cuisine', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Enter the type of cuisine served (only for food businesses).', 'nexter-extension' ),
		'default' => '',
	),
	array(
		'key'     => 'address',
		'subkey'  => '@type',
		'label'   => __( 'Address Type', 'nexter-extension' ),
		'input'   => 'text',
		'default' => 'PostalAddress',
	),
	array(
		'key'     => 'address',
		'subkey'  => 'streetAddress',
		'label'   => __( 'Street Address', 'nexter-extension' ),
		'input'   => 'editor',
		'default' => '%website_details.website_owner_address%',
	),
	array(
		'key'     => 'address',
		'subkey'  => 'addressLocality',
		'label'   => __( 'City', 'nexter-extension' ),
		'input'   => 'editor',
		'default' => '',
	),
	array(
		'key'     => 'address',
		'subkey'  => 'addressRegion',
		'label'   => __( 'State / Region', 'nexter-extension' ),
		'input'   => 'editor',
		'default' => '',
	),
	array(
		'key'     => 'address',
		'subkey'  => 'postalCode',
		'label'   => __( 'Postal Code', 'nexter-extension' ),
		'input'   => 'editor',
		'default' => '',
	),
	array(
		'key'     => 'address',
		'subkey'  => 'addressCountry',
		'label'   => __( 'Country', 'nexter-extension' ),
		'input'   => 'editor',
		'default' => '',
	),
	array(
		'key'     => 'geo',
		'subkey'  => '@type',
		'label'   => __( 'Geo Type', 'nexter-extension' ),
		'input'   => 'text',
		'default' => 'GeoCoordinates',
	),
	array(
		'key'     => 'geo',
		'subkey'  => 'latitude',
		'label'   => __( 'Latitude', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Enter the decimal latitude (for example: 37.42242).', 'nexter-extension' ),
		'default' => '',
	),
	array(
		'key'     => 'geo',
		'subkey'  => 'longitude',
		'label'   => __( 'Longitude', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Enter the decimal longitude (for example: -122.08585).', 'nexter-extension' ),
		'default' => '',
	),
	array(
		'key'     => 'areaServed',
		'label'   => __( 'Area Served', 'nexter-extension' ),
		'input'   => 'editor',
		'default' => '',
	),
	array(
		'key'     => 'acceptsReservations',
		'label'   => __( 'Accepts Reservations', 'nexter-extension' ),
		'input'   => 'select_group',
		'tooltip' => __( 'Select if the business allows customers to book or make reservations.', 'nexter-extension' ),
		'default' => 'False',
		'options' => nexter_content_seo_schema_local_business_accepts_reservations_groups(),
	),
	array(
		'key'     => 'hasMap',
		'label'   => __( 'Map URL', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Add the URL to a map showing the business location.', 'nexter-extension' ),
		'default' => '',
	),
	array(
		'key'     => 'currenciesAccepted',
		'label'   => __( 'Currencies Accepted', 'nexter-extension' ),
		'input'   => 'editor',
		'default' => '',
	),
	array(
		'key'     => 'paymentAccepted',
		'label'   => __( 'Payment Accepted', 'nexter-extension' ),
		'input'   => 'editor',
		'default' => '',
	),
	array(
		'key'     => 'priceRange',
		'label'   => __( 'Price Range', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Enter the price range (for example: $10-15 or $$$).', 'nexter-extension' ),
		'default' => '',
	),
	array(
		'key'     => 'telephone',
		'label'   => __( 'Phone', 'nexter-extension' ),
		'input'   => 'editor',
		'default' => '%website_details.website_owner_phone%',
	),
	array(
		'key'     => 'email',
		'label'   => __( 'Email', 'nexter-extension' ),
		'input'   => 'editor',
		'default' => '%website_details.website_owner_email%',
	),
	array(
		'key'     => 'faxNumber',
		'label'   => __( 'Fax', 'nexter-extension' ),
		'input'   => 'editor',
		'default' => '',
	),
	array(
		'key'     => 'openingHoursSpecification',
		'label'   => __( 'Opening Hours', 'nexter-extension' ),
		'input'   => 'local_business_opening_hours_list',
		'default' => array(),
	),
	array(
		'key'     => 'brand',
		'label'   => __( 'Brands', 'nexter-extension' ),
		'input'   => 'local_business_brand_list',
		'default' => array(),
	),
	array(
		'key'     => 'contactPoint',
		'label'   => __( 'Contact Points', 'nexter-extension' ),
		'input'   => 'local_business_contact_point_list',
		'default' => array(),
	),
	array(
		'key'     => 'location',
		'label'   => __( 'Locations', 'nexter-extension' ),
		'input'   => 'local_business_place_list',
		'tooltip' => __( 'Add any additional physical or virtual business locations.', 'nexter-extension' ),
		'default' => array(),
	),
	array(
		'key'     => 'employee',
		'label'   => __( 'Employees', 'nexter-extension' ),
		'input'   => 'local_business_employee_list',
		'default' => array(),
	),
	array(
		'key'     => 'founder',
		'label'   => __( 'Founders', 'nexter-extension' ),
		'input'   => 'person_list',
		'default' => array(),
	),
	array(
		'key'     => 'funder',
		'label'   => __( 'Funders', 'nexter-extension' ),
		'input'   => 'person_list',
		'default' => array(),
	),
	array(
		'key'     => 'sponsor',
		'label'   => __( 'Sponsors', 'nexter-extension' ),
		'input'   => 'person_list',
		'default' => array(),
	),
	array(
		'key'     => 'alumni',
		'label'   => __( 'Alumni', 'nexter-extension' ),
		'input'   => 'person_list',
		'default' => array(),
	),
	array(
		'key'     => 'hasPOS',
		'label'   => __( 'Point Of Sale Locations', 'nexter-extension' ),
		'input'   => 'local_business_place_list',
		'default' => array(),
	),
	array(
		'key'     => 'foundingLocation',
		'label'   => __( 'Founding Location', 'nexter-extension' ),
		'input'   => 'local_business_founding_place_list',
		'tooltip' => __( 'Enter where the organization was originally founded.', 'nexter-extension' ),
		'default' => array(),
	),
	array(
		'key'     => 'department',
		'label'   => __( 'Departments', 'nexter-extension' ),
		'input'   => 'string_list',
		'default' => array(),
	),
	array(
		'key'     => 'parentOrganization',
		'label'   => __( 'Parent Organization', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Enter the name of the parent organization if any.', 'nexter-extension' ),
		'default' => '',
	),
	array(
		'key'     => 'numberOfEmployees',
		'subkey'  => '@type',
		'label'   => __( 'Employee Count Type', 'nexter-extension' ),
		'input'   => 'text',
		'default' => 'QuantitativeValue',
	),
	array(
		'key'     => 'numberOfEmployees',
		'subkey'  => 'value',
		'label'   => __( 'Number Of Employees', 'nexter-extension' ),
		'input'   => 'editor',
		'default' => '',
	),
	array(
		'key'     => 'duns',
		'label'   => __( 'DUNS', 'nexter-extension' ),
		'input'   => 'editor',
		'default' => '',
	),
	array(
		'key'     => 'globalLocationNumber',
		'label'   => __( 'Global Location Number (GLN)', 'nexter-extension' ),
		'input'   => 'editor',
		'default' => '',
	),
	array(
		'key'     => 'isicV4',
		'label'   => __( 'ISIC V4', 'nexter-extension' ),
		'input'   => 'editor',
		'default' => '',
	),
	array(
		'key'     => 'iso6523Code',
		'label'   => __( 'ISO 6523 Code', 'nexter-extension' ),
		'input'   => 'editor',
		'default' => '',
	),
	array(
		'key'     => 'leiCode',
		'label'   => __( 'LEI Code', 'nexter-extension' ),
		'input'   => 'editor',
		'default' => '',
	),
	array(
		'key'     => 'naics',
		'label'   => __( 'NAICS', 'nexter-extension' ),
		'input'   => 'editor',
		'default' => '',
	),
	array(
		'key'     => 'taxID',
		'label'   => __( 'Tax ID', 'nexter-extension' ),
		'input'   => 'editor',
		'default' => '',
	),
	array(
		'key'     => 'vatID',
		'label'   => __( 'VAT ID', 'nexter-extension' ),
		'input'   => 'editor',
		'default' => '',
	),
	array(
		'key'     => 'award',
		'label'   => __( 'Award', 'nexter-extension' ),
		'input'   => 'editor',
		'default' => '',
	),
	array(
		'key'     => 'foundingDate',
		'label'   => __( 'Founding Date', 'nexter-extension' ),
		'input'   => 'editor',
		'default' => '',
	),
	array(
		'key'     => 'keywords',
		'label'   => __( 'Keywords', 'nexter-extension' ),
		'input'   => 'editor',
		'default' => '',
	),
	array(
		'key'     => 'knowsLanguage',
		'label'   => __( 'Languages', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Add languages spoken or supported by the business (separated by commas).', 'nexter-extension' ),
		'default' => '%site.language%',
	),
	array(
		'key'     => 'legalName',
		'label'   => __( 'Legal Name', 'nexter-extension' ),
		'input'   => 'editor',
		'default' => '',
	),
	array(
		'key'     => 'slogan',
		'label'   => __( 'Slogan', 'nexter-extension' ),
		'input'   => 'editor',
		'default' => '',
	),
	array(
		'key'     => 'owns',
		'label'   => __( 'Products Owned', 'nexter-extension' ),
		'input'   => 'string_list',
		'default' => array(),
	),
	array(
		'key'     => 'sameAs',
		'label'   => __( 'Same As', 'nexter-extension' ),
		'input'   => 'string_list',
		'tooltip' => __( 'Add social media or other official profile URLs.', 'nexter-extension' ),
		'default' => array(),
	),
	array(
		'key'     => 'mainEntityOfPage',
		'label'   => __( 'Main Entity Of Page', 'nexter-extension' ),
		'input'   => 'editor',
		'default' => '',
	),
);
