<?php
/**
 * Field definitions: VideoObject (Schema.org VideoObject).
 *
 * @package Nexter_Extension
 * @subpackage Content_SEO
 */

defined( 'ABSPATH' ) || exit;

require_once __DIR__ . '/video-object-selects.php';

return array(
	array(
		'key'     => '@id',
		'label'   => __( 'ID', 'nexter-extension' ),
		'input'   => 'text',
		'tooltip' => __( 'A unique ID for this schema. You can use the page URL or leave the default value as it is.', 'nexter-extension' ),
		'default' => '%post.url%#video-%schema.item.id%',
	),
	array(
		'key'     => '@type',
		'label'   => __( 'Type', 'nexter-extension' ),
		'input'   => 'text',
		'tooltip' => __( 'Set the schema type. This should always be set to VideoObject.', 'nexter-extension' ),
		'default' => 'VideoObject',
	),
	array(
		'key'     => 'name',
		'label'   => __( 'Name', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Enter the name or title of the video.', 'nexter-extension' ),
		'default' => '%post.title%',
	),
	array(
		'key'     => 'description',
		'label'   => __( 'Description', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Write a short summary of the video content.', 'nexter-extension' ),
		'default' => '%post.excerpt%',
	),
	array(
		'key'     => 'thumbnailUrl',
		'label'   => __( 'Thumbnail URL', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Add the link to the image that will be shown before the video plays.', 'nexter-extension' ),
		'default' => '%post.thumbnail%',
	),
	array(
		'key'     => 'uploadDate',
		'label'   => __( 'Upload Date', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Enter the date when the video was uploaded.', 'nexter-extension' ),
		'default' => '%post.date_c%',
	),
	array(
		'key'     => 'duration',
		'label'   => __( 'Duration', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Enter how long the video lasts (for example: 5 minutes or PT5M).', 'nexter-extension' ),
		'default' => '',
	),
	array(
		'key'     => 'contentUrl',
		'label'   => __( 'Content URL', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Add the link directly to the video file (for example: .mp4).', 'nexter-extension' ),
		'default' => '',
	),
	array(
		'key'     => 'embedUrl',
		'label'   => __( 'Embed URL', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Add the link to the player if the video is embedded from another site (like YouTube).', 'nexter-extension' ),
		'default' => '',
	),
	array(
		'key'     => 'interactionStatistic',
		'subkey'  => '@type',
		'label'   => __( 'Interaction Statistic Type', 'nexter-extension' ),
		'input'   => 'text',
		'default' => 'InteractionCounter',
	),
	array(
		'key'     => 'interactionStatistic',
		'subkey'  => 'interactionType',
		'label'   => __( 'Interaction Type', 'nexter-extension' ),
		'input'   => 'select_group',
		'tooltip' => __( 'Select the type of interaction for the video (usually set to WatchAction).', 'nexter-extension' ),
		'default' => 'http://schema.org/WatchAction',
		'options' => nexter_content_seo_schema_video_interaction_type_groups(),
	),
	array(
		'key'     => 'interactionStatistic',
		'subkey'  => 'userInteractionCount',
		'label'   => __( 'User Interaction Count', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Enter the number of times the video has been watched or interacted with.', 'nexter-extension' ),
		'default' => '',
	),
	array(
		'key'     => 'publisher',
		'subkey'  => '@type',
		'label'   => __( 'Publisher Type', 'nexter-extension' ),
		'input'   => 'text',
		'default' => 'Organization',
	),
	array(
		'key'     => 'publisher',
		'subkey'  => 'name',
		'label'   => __( 'Publisher Name', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Enter the name of the organization that published the video.', 'nexter-extension' ),
		'default' => '%site.title%',
	),
	array(
		'key'     => 'publisher',
		'subkey'  => 'logo',
		'label'   => __( 'Publisher Logo', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Add the link to the logo of the publishing organization.', 'nexter-extension' ),
		'default' => '%website_details.website_logo%',
	),
	array(
		'key'     => 'author',
		'subkey'  => '@type',
		'label'   => __( 'Author Type', 'nexter-extension' ),
		'input'   => 'text',
		'default' => 'Person',
	),
	array(
		'key'     => 'author',
		'subkey'  => 'name',
		'label'   => __( 'Author Name', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Enter the name of the person who created the video.', 'nexter-extension' ),
		'default' => '%author.display_name%',
	),
	array(
		'key'     => 'author',
		'subkey'  => 'url',
		'label'   => __( 'Author URL', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Add the link to the author’s profile or website.', 'nexter-extension' ),
		'default' => '%author.posts_url%',
	),
	array(
		'key'     => 'genre',
		'label'   => __( 'Genre', 'nexter-extension' ),
		'input'   => 'editor',
		'default' => '',
	),
	array(
		'key'     => 'keywords',
		'label'   => __( 'Keywords', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Add terms or tags that describe the video content (separated by commas).', 'nexter-extension' ),
		'default' => '%post.tags%',
	),
	array(
		'key'     => 'videoFrameSize',
		'label'   => __( 'Video Frame Size', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Enter the dimensions of the video (for example: 1920x1080).', 'nexter-extension' ),
		'default' => '',
	),
	array(
		'key'     => 'videoQuality',
		'label'   => __( 'Video Quality', 'nexter-extension' ),
		'input'   => 'select_group',
		'default' => '',
		'options' => nexter_content_seo_schema_video_quality_groups(),
	),
	array(
		'key'     => 'inLanguage',
		'label'   => __( 'Language', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Enter the language used in the video (for example: en-US).', 'nexter-extension' ),
		'default' => '%site.language%',
	),
	array(
		'key'     => 'transcript',
		'label'   => __( 'Transcript', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Add the text or a link to the video transcript.', 'nexter-extension' ),
		'default' => '',
	),
	array(
		'key'     => 'caption',
		'label'   => __( 'Caption', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Add the link to the video caption file (optional).', 'nexter-extension' ),
		'default' => '',
	),
	array(
		'key'     => 'expires',
		'label'   => __( 'Expires', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Enter the date when the video will no longer be available (optional).', 'nexter-extension' ),
		'default' => '',
	),
	array(
		'key'     => 'regionsAllowed',
		'label'   => __( 'Regions Allowed', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'List the countries or regions where the video can be watched (optional).', 'nexter-extension' ),
		'default' => '',
	),
	array(
		'key'     => 'requiresSubscription',
		'label'   => __( 'Requires Subscription', 'nexter-extension' ),
		'input'   => 'select_group',
		'tooltip' => __( 'Select if the video is free or needs a subscription to watch.', 'nexter-extension' ),
		'default' => 'false',
		'options' => nexter_content_seo_schema_video_yes_no_groups(),
	),
	array(
		'key'     => 'isFamilyFriendly',
		'label'   => __( 'Family Friendly', 'nexter-extension' ),
		'input'   => 'select_group',
		'default' => 'true',
		'options' => nexter_content_seo_schema_video_yes_no_groups(),
	),
	array(
		'key'     => 'contentRating',
		'label'   => __( 'Content Rating', 'nexter-extension' ),
		'input'   => 'select_group',
		'tooltip' => __( 'Select the audience rating for the video (for example: G, PG-13, R).', 'nexter-extension' ),
		'default' => '',
		'options' => nexter_content_seo_schema_video_content_rating_groups(),
	),
	array(
		'key'     => 'isPartOf',
		'label'   => __( 'Is Part Of', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Use this if the video is part of a larger page or article (optional).', 'nexter-extension' ),
		'default' => '%schemas.webpage%',
	),
	array(
		'key'     => 'mainEntityOfPage',
		'label'   => __( 'Main Entity Of Page', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Define what the page is mainly about (for example: article, product, or video).', 'nexter-extension' ),
		'default' => '',
	),
);
