<?php
/**
 * Field definitions: Recipe (Schema.org Recipe).
 *
 * @package Nexter_Extension
 * @subpackage Content_SEO
 */

defined( 'ABSPATH' ) || exit;

return array(
	array(
		'key'     => '@id',
		'label'   => __( 'ID', 'nexter-extension' ),
		'input'   => 'text',
		'tooltip' => __( 'A unique ID for this schema. You can use the page URL or leave the default value as it is.', 'nexter-extension' ),
		'default' => '%post.url%#recipe-%schema.item.id%',
	),
	array(
		'key'     => '@type',
		'label'   => __( 'Type', 'nexter-extension' ),
		'input'   => 'text',
		'tooltip' => __( 'Set the schema type. This should always be set to Recipe.', 'nexter-extension' ),
		'default' => 'Recipe',
	),
	array(
		'key'     => 'name',
		'label'   => __( 'Recipe Name', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Enter the full name of the recipe.', 'nexter-extension' ),
		'default' => '%post.title%',
	),
	array(
		'key'     => 'description',
		'label'   => __( 'Description', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Add a short summary of the dish.', 'nexter-extension' ),
		'default' => '%post.excerpt%',
	),
	array(
		'key'     => 'image',
		'label'   => __( 'Recipe Image', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Add the URL of an image showing the finished dish.', 'nexter-extension' ),
		'default' => '%post.thumbnail%',
	),
	array(
		'key'     => 'recipeCategory',
		'label'   => __( 'Meal Type', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Choose the type of meal (for example: Dinner, Dessert, Appetizer).', 'nexter-extension' ),
		'default' => '',
	),
	array(
		'key'     => 'recipeCuisine',
		'label'   => __( 'Cuisine', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Enter the culinary tradition (for example: Italian, Mexican).', 'nexter-extension' ),
		'default' => '',
	),
	array(
		'key'     => 'keywords',
		'label'   => __( 'Keywords', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Add keywords like Healthy, Quick, or Vegetarian.', 'nexter-extension' ),
		'default' => '',
	),
	array(
		'key'     => 'recipeYield',
		'label'   => __( 'Yield / Servings', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Enter how many servings the recipe makes (for example: 4 servings).', 'nexter-extension' ),
		'default' => '',
	),
	array(
		'key'     => 'author',
		'subkey'  => '@type',
		'label'   => __( 'Author Type', 'nexter-extension' ),
		'input'   => 'text',
		'default' => 'Person',
	),
	array(
		'key'     => 'author',
		'subkey'  => 'name',
		'label'   => __( 'Author Name', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Enter the name of the person who wrote the recipe.', 'nexter-extension' ),
		'default' => '%author.display_name%',
	),
	array(
		'key'     => 'datePublished',
		'label'   => __( 'Date Published', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Enter the date when the recipe was published.', 'nexter-extension' ),
		'default' => '%post.date_c%',
	),
	array(
		'key'     => 'totalTime',
		'label'   => __( 'Total Time', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Enter the total time from start to finish (for example: 1 hour).', 'nexter-extension' ),
		'default' => '',
	),
	array(
		'key'     => 'prepTime',
		'label'   => __( 'Prep Time', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Enter the time needed for preparation.', 'nexter-extension' ),
		'default' => '',
	),
	array(
		'key'     => 'cookTime',
		'label'   => __( 'Cook Time', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Enter the active cooking time.', 'nexter-extension' ),
		'default' => '',
	),
	array(
		'key'     => 'recipeIngredient',
		'label'   => __( 'Ingredients', 'nexter-extension' ),
		'input'   => 'string_list',
		'tooltip' => __( 'Add the ingredients needed, one per line.', 'nexter-extension' ),
		'default' => array(),
	),
	array(
		'key'     => 'recipeInstructions',
		'label'   => __( 'Instructions', 'nexter-extension' ),
		'input'   => 'how_to_step_list',
		'tooltip' => __( 'Add the cooking instructions step by step.', 'nexter-extension' ),
		'default' => array(),
	),
	array(
		'key'     => 'nutrition',
		'subkey'  => '@type',
		'label'   => __( 'Nutrition Type', 'nexter-extension' ),
		'input'   => 'text',
		'default' => 'NutritionInformation',
	),
	array(
		'key'     => 'nutrition',
		'subkey'  => 'calories',
		'label'   => __( 'Calories', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Enter the calories per serving (for example: 270 cal).', 'nexter-extension' ),
		'default' => '',
	),
	array(
		'key'     => 'nutrition',
		'subkey'  => 'fatContent',
		'label'   => __( 'Fat', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Enter the amount of fat per serving (for example: 15g).', 'nexter-extension' ),
		'default' => '',
	),
	array(
		'key'     => 'nutrition',
		'subkey'  => 'carbohydrateContent',
		'label'   => __( 'Carbohydrates', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Enter the amount of carbohydrates per serving (for example: 45g).', 'nexter-extension' ),
		'default' => '',
	),
	array(
		'key'     => 'nutrition',
		'subkey'  => 'proteinContent',
		'label'   => __( 'Protein', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Enter the amount of protein per serving (for example: 20g).', 'nexter-extension' ),
		'default' => '',
	),
	array(
		'key'     => 'nutrition',
		'subkey'  => 'fiberContent',
		'label'   => __( 'Fiber', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Enter the amount of fiber per serving (for example: 8g).', 'nexter-extension' ),
		'default' => '',
	),
	array(
		'key'     => 'nutrition',
		'subkey'  => 'sugarContent',
		'label'   => __( 'Sugar', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Enter the amount of sugar per serving (for example: 12g).', 'nexter-extension' ),
		'default' => '',
	),
	array(
		'key'     => 'nutrition',
		'subkey'  => 'sodiumContent',
		'label'   => __( 'Sodium', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Enter the amount of sodium per serving (for example: 600mg).', 'nexter-extension' ),
		'default' => '',
	),
	array(
		'key'     => 'aggregateRating',
		'subkey'  => 'ratingValue',
		'label'   => __( 'Rating Value', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Enter the average rating for the recipe.', 'nexter-extension' ),
		'default' => '',
	),
	array(
		'key'     => 'aggregateRating',
		'subkey'  => 'reviewCount',
		'label'   => __( 'Review Count', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Enter the total number of ratings or reviews.', 'nexter-extension' ),
		'default' => '',
	),
	array(
		'key'     => 'isPartOf',
		'label'   => __( 'Is Part Of', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Use this if the recipe belongs to a larger section or website (optional).', 'nexter-extension' ),
		'default' => '%schemas.webpage%',
	),
	array(
		'key'     => 'mainEntityOfPage',
		'label'   => __( 'Main Entity Of Page', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Define what the page is mainly about (for example: article, product, or recipe).', 'nexter-extension' ),
		'default' => '',
	),
);
