<?php
/**
 * Field definitions: SoftwareApplication (Schema.org SoftwareApplication).
 *
 * @package Nexter_Extension
 * @subpackage Content_SEO
 */

defined( 'ABSPATH' ) || exit;

require_once __DIR__ . '/software-application-selects.php';

return array(
	array(
		'key'     => '@id',
		'label'   => __( 'ID', 'nexter-extension' ),
		'input'   => 'text',
		'tooltip' => __( 'A unique ID for this schema. You can use the page URL or leave the default value as it is.', 'nexter-extension' ),
		'default' => '%post.url%#software-%schema.item.id%',
	),
	array(
		'key'     => '@type',
		'label'   => __( 'Type', 'nexter-extension' ),
		'input'   => 'text',
		'tooltip' => __( 'Set the schema type. This should always be set to SoftwareApplication.', 'nexter-extension' ),
		'default' => 'SoftwareApplication',
	),
	array(
		'key'     => '_software_additional_types',
		'label'   => __( 'Additional Application Types', 'nexter-extension' ),
		'input'   => 'string_list',
		'tooltip' => __( 'Choose additional types if applicable (for example: MobileApplication, WebApplication, or VideoGame).', 'nexter-extension' ),
		'default' => array( 'WebApplication' ),
	),
	array(
		'key'     => 'name',
		'label'   => __( 'Name', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Enter the full name of the software.', 'nexter-extension' ),
		'default' => '%post.title%',
	),
	array(
		'key'     => 'offers',
		'subkey'  => '@type',
		'label'   => __( 'Offer Type', 'nexter-extension' ),
		'input'   => 'text',
		'default' => 'Offer',
	),
	array(
		'key'     => 'offers',
		'subkey'  => 'name',
		'label'   => __( 'Offer Name', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Enter a name for this offer (for example: Free Version, Pro Plan).', 'nexter-extension' ),
		'default' => '%post.title%',
	),
	array(
		'key'     => 'offers',
		'subkey'  => 'acceptedPaymentMethod',
		'label'   => __( 'Accepted Payment Method', 'nexter-extension' ),
		'input'   => 'select_group',
		'tooltip' => __( 'Select the payment methods you accept for this software.', 'nexter-extension' ),
		'default' => 'http://purl.org/goodrelations/v1#Cash',
		'options' => nexter_content_seo_schema_software_offer_payment_groups(),
	),
	array(
		'key'     => 'offers',
		'subkey'  => 'price',
		'label'   => __( 'Price', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Enter the price of the software application.', 'nexter-extension' ),
		'default' => '',
	),
	array(
		'key'     => 'offers',
		'subkey'  => 'priceCurrency',
		'label'   => __( 'Price Currency', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Enter the currency code (for example: USD, EUR).', 'nexter-extension' ),
		'default' => 'USD',
	),
	array(
		'key'     => 'offers',
		'subkey'  => 'priceValidUntil',
		'label'   => __( 'Price Valid Until', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Enter the date when this price offer ends.', 'nexter-extension' ),
		'default' => '',
	),
	array(
		'key'     => 'offers',
		'subkey'  => 'seller',
		'label'   => __( 'Seller', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Enter the name of the person or organization selling the software.', 'nexter-extension' ),
		'default' => '',
	),
	array(
		'key'     => 'offers',
		'subkey'  => 'serialNumber',
		'label'   => __( 'Serial Number', 'nexter-extension' ),
		'input'   => 'editor',
		'default' => '',
	),
	array(
		'key'     => 'offers',
		'subkey'  => 'sku',
		'label'   => __( 'SKU', 'nexter-extension' ),
		'input'   => 'editor',
		'default' => '',
	),
	array(
		'key'     => 'applicationCategory',
		'label'   => __( 'Application Category', 'nexter-extension' ),
		'input'   => 'select_group',
		'tooltip' => __( 'Choose the category that best describes your software.', 'nexter-extension' ),
		'default' => 'GameApplication',
		'options' => nexter_content_seo_schema_software_application_category_groups(),
	),
	array(
		'key'     => 'applicationSubCategory',
		'label'   => __( 'Application Subcategory', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Enter a subcategory if needed (for example: Arcade Game, Photo Editor).', 'nexter-extension' ),
		'default' => '',
	),
	array(
		'key'     => 'applicationSuite',
		'label'   => __( 'Application Suite', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Enter the name of the software suite this app belongs to (if any).', 'nexter-extension' ),
		'default' => '',
	),
	array(
		'key'     => 'carrierRequirements',
		'label'   => __( 'Carrier Requirements', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Enter any specific mobile carrier requirements.', 'nexter-extension' ),
		'default' => '',
	),
	array(
		'key'     => 'browserRequirements',
		'label'   => __( 'Browser Requirements', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Enter the browser requirements for web applications.', 'nexter-extension' ),
		'default' => '',
	),
	array(
		'key'     => 'actor',
		'label'   => __( 'Actor', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'List any actors featured in the game (for Video Games).', 'nexter-extension' ),
		'default' => '',
	),
	array(
		'key'     => 'director',
		'label'   => __( 'Director', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Enter the name of the director (for Video Games).', 'nexter-extension' ),
		'default' => '',
	),
	array(
		'key'     => 'cheatCode',
		'label'   => __( 'Cheat Code', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Add any cheat codes for the game (for Video Games).', 'nexter-extension' ),
		'default' => '',
	),
	array(
		'key'     => 'gameEdition',
		'label'   => __( 'Game Edition', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Enter the specific edition of the game.', 'nexter-extension' ),
		'default' => '',
	),
	array(
		'key'     => 'gamePlatform',
		'label'   => __( 'Game Platform', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'List the platforms the game is available on (for example: PC, PlayStation).', 'nexter-extension' ),
		'default' => '',
	),
	array(
		'key'     => 'musicBy',
		'label'   => __( 'Music By', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Enter the name of the music composer.', 'nexter-extension' ),
		'default' => '',
	),
	array(
		'key'     => 'playMode',
		'label'   => __( 'Play Mode', 'nexter-extension' ),
		'input'   => 'select_group',
		'tooltip' => __( 'Select the play modes supported (for example: Single-player, Multiplayer).', 'nexter-extension' ),
		'default' => '',
		'options' => nexter_content_seo_schema_software_play_mode_groups(),
	),
	array(
		'key'     => 'trailer',
		'label'   => __( 'Trailer', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Add the link to the game trailer video.', 'nexter-extension' ),
		'default' => '',
	),
	array(
		'key'     => 'availableOnDevice',
		'label'   => __( 'Available On Device', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'List the devices required to run the application.', 'nexter-extension' ),
		'default' => '',
	),
	array(
		'key'     => 'countriesSupported',
		'label'   => __( 'Countries Supported', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Enter the countries where the application is available.', 'nexter-extension' ),
		'default' => '',
	),
	array(
		'key'     => 'countriesNotSupported',
		'label'   => __( 'Countries Not Supported', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Enter the countries where the application is not available.', 'nexter-extension' ),
		'default' => '',
	),
	array(
		'key'     => 'downloadUrl',
		'label'   => __( 'Download URL', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Add the link to download the software.', 'nexter-extension' ),
		'default' => '',
	),
	array(
		'key'     => 'featureList',
		'label'   => __( 'Feature List', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Add a list of features or modules included in the software.', 'nexter-extension' ),
		'default' => '',
	),
	array(
		'key'     => 'fileSize',
		'label'   => __( 'File Size', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Enter the size of the application file (for example: 18MB).', 'nexter-extension' ),
		'default' => '',
	),
	array(
		'key'     => 'installUrl',
		'label'   => __( 'Install URL', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Add the link where the application can be installed.', 'nexter-extension' ),
		'default' => '',
	),
	array(
		'key'     => 'memoryRequirements',
		'label'   => __( 'Memory Requirements', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Enter the minimum RAM or memory required.', 'nexter-extension' ),
		'default' => '',
	),
	array(
		'key'     => 'releaseNotes',
		'label'   => __( 'Release Notes', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Describe what has changed in this version of the software.', 'nexter-extension' ),
		'default' => '',
	),
	array(
		'key'     => 'operatingSystem',
		'label'   => __( 'Operating System', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'List the operating systems required to run the software.', 'nexter-extension' ),
		'default' => '',
	),
	array(
		'key'     => 'permissions',
		'label'   => __( 'Permissions', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'List any special permissions required by the software.', 'nexter-extension' ),
		'default' => '',
	),
	array(
		'key'     => 'processorRequirements',
		'label'   => __( 'Processor Requirements', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Enter the processor or CPU requirements.', 'nexter-extension' ),
		'default' => '',
	),
	array(
		'key'     => 'screenshot',
		'label'   => __( 'Screenshot', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Add the URL of a screenshot showing the software in action.', 'nexter-extension' ),
		'default' => '',
	),
	array(
		'key'     => 'softwareRequirements',
		'label'   => __( 'Software Requirements', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'List any other software or libraries required (for example: .NET, Java).', 'nexter-extension' ),
		'default' => '',
	),
	array(
		'key'     => 'softwareVersion',
		'label'   => __( 'Software Version', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Enter the current version number of the software.', 'nexter-extension' ),
		'default' => '',
	),
	array(
		'key'     => 'storageRequirements',
		'label'   => __( 'Storage Requirements', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Enter the minimum disk space required.', 'nexter-extension' ),
		'default' => '',
	),
	array(
		'key'     => 'isPartOf',
		'label'   => __( 'Is Part Of', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Use this if the software is part of a larger website or series (optional).', 'nexter-extension' ),
		'default' => '%schemas.webpage%',
	),
	array(
		'key'     => 'mainEntityOfPage',
		'label'   => __( 'Main Entity Of Page', 'nexter-extension' ),
		'input'   => 'editor',
		'tooltip' => __( 'Define what the page is mainly about (for example: article, product, or software).', 'nexter-extension' ),
		'default' => '',
	),
);
